accepted = [
    "MIT",
    "Apache-2.0",
    "BSD-3-Clause",
    "BSD-2-Clause",
    "ISC",
    "Zlib",
    "MPL-2.0",
    "Unlicense",
    "CC0-1.0",
    "Unicode-3.0",
    "Unicode-DFS-2016",
    "GPL-2.0",
    "GPL-2.0-only",
    "GPL-2.0-or-later",
    "GPL-3.0", 
    "LGPL-3.0",
    "Apache-2.0 WITH LLVM-exception",
]

# targets = []

# If a crate uses a license not in 'accepted', we can specify it here to allow it anyway
# [exceptions]
# "crate-name" = "License-Name"
